			</div><!-- #ontainer-content-2 -->
        </div><!-- #ontainer-content -->
	<div id="footer-external">
		<ul id="footer-external-links">
                <p>This web page is maintained by informaticians within <a href="http://www.csiro.au/en/Research/LWF">CSIRO Land &amp; Water</a>. See the <a href="/contact">Contact</a> page for more info.</p>
	        	<li>CSIRO links: </li>
                <li>|</li>
                <li class="last"><a href="http://www.csiro.au/en/About/We-are-CSIRO">More about CSIRO</a></li>
		        <li><a href="http://www.csiro.au/Copyright.aspx">Copyright</a></li>
		        <li>|</li>
		        <li><a href="http://www.csiro.au/Legal-Notice-and-Disclaimer.aspx">Legal Notice and Disclaimer</a></li>
		        <li>|</li>
		        <li><a href="http://www.csiro.au/Privacy.aspx">Privacy</a></li>
		        <li>|</li>
		        <li><a href="http://www.csiro.au/Accessibility.aspx">Accessibility</a></li>
		</ul>
	</div><!-- footer external -->
    </body>
</html>
