<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>promsns.org</title>
        <meta content="Welcome to the Commonwealth Scientific and Industrial Research Organisation (CSIRO)" name="title">
        <link rel="schema.dc" href="http://purl.org/dc/elements/1.1/" />
        <link rel="schema.dcterms" href="http://purl.org/dc/terms/" />
        <meta name="dc.identifier" content="http://promsns.org" />
        <meta name="dc.language" content="en-au" />
        <meta name="dc.format" content="text/html" />
        <meta name="dcterms.creator" content="Nicholas Car <nicholas.car@csiro.au>" />
        <meta name="dcterms.publisher" content="CSIRO <http://www.csiro.au>" />
        <meta name="dcterms.title" content="<?php echo $title; ?>" />
        <meta name="dcterms.description" content="All about <?php echo $title; ?>" />
        <meta name="description" content="All about <?php echo $title; ?>"  />
        <meta name="dcterms.created" content="2015-11-20" />
        <meta name="dcterms.modified" content="2018-03-08" />
        <meta name="dcterms.rights" content="https://opensource.org/licenses/MIT" />
        <link rel="stylesheet" type="text/css" href="<?php echo $root_path ?>theme/css/csiro_theme.css" media="screen, projection" />
        <link rel="stylesheet" type="text/css" href="<?php echo $root_path ?>theme/css/nc_theme.css" />
        <link rel="icon" href="theme/img/favicon.ico" />
        </head>
        <body>
            <div id="container-logo">
                <img id="csiro-logo" src="<?php echo $root_path ?>theme/img/logo.png" />
              	<div id="navblue-container">
              		<span id="navblue">
              			<?php include 'nav.inc' ?>
              		</span>
              	</div>
                  </div>
                  <div id="container-content">
                    <div id="container-content-2">
